#! /usr/bin/env bash
[ -r ~/.epiquery2/config ] && . ~/.epiquery2/config
if [ -n "${TEMPLATE_REPO_URL}" ]; then
  TEMPLATE_ORIGIN_URL=${TEMPLATE_REPO_URL}
else
  MY_ORIGIN_URL=`git config -l | grep remote.origin.url | sed -e s[remote.origin.url=[[g`
  REPO_NAME=`basename ${MY_ORIGIN_URL}`
  ORIGIN_ROOT=${MY_ORIGIN_URL%/${REPO_NAME}}
  TEMPLATES_REPO_NAME=${REPO_NAME/.git/-templates.git}
  TEMPLATE_ORIGIN_URL=${ORIGIN_ROOT}/${TEMPLATES_REPO_NAME}
fi

if [ -d templates ]; then
  rm -rf ./templates
fi
echo "fetching templates from ${TEMPLATE_ORIGIN_URL}"
git clone ${TEMPLATE_ORIGIN_URL} templates
npm install --production .

