version: "3"
services:
  mysql:
    image: mysql:5.7.11
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_root_password
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=epiquery
  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=YourV3ryStrong!Passw0rd
  epiquery:
    build: .
    environment:
      - PORT=8080
      - TEMPLATE_DIRECTORY=/var/app/difftest/templates
      - CONNECTIONS=EPI_C_MSSQL_O EPI_C_MSSQL EPI_C_FILE EPI_C_MYSQL EPI_C_RENDER SFDC NON_EXISTENT_SERVER EPI_C_TIMESOUT EPI_C_MYSQL_BULK
      - EPI_C_FILE={"driver":"file","config":{},"name":"file"}
      - EPI_C_RENDER={"driver":"render","config":{},"name":"render"}
      - EPI_C_MSSQL={"driver":"mssql","name":"mssql","config":{"server":"mssql","password":"YourV3ryStrong!Passw0rd","userName":"SA","options":{"port":1433, "requestTimeout":0}}}
      - EPI_C_MSSQL_O={"driver":"mssql_o","name":"mssql_o","config":{"server":"mssql","password":"YourV3ryStrong!Passw0rd","userName":"SA","options":{"port":1433, "requestTimeout":0}}}
      - EPI_C_TIMESOUT={"driver":"mssql","name":"timesout","config":{"server":"localhost","password":"vagrant","userName":"vagrant","options":{"port":1433, "requestTimeout":1}}}
      - EPI_C_MYSQL={"name":"mysql","driver":"mysql","config":{"host":"mysql","user":"root","password":"mysql_root_password"}}
      - EPI_C_MYSQL_BULK={"name":"mysql_bulk", "type":"bulk","driver":"mysql","config":{"host":"mysql","user":"root","password":"mysql_root_password"}}
      - SFDC={"name":"sfdc","driver":"salesforce","config":{"userName":"financeintegration@glgroup.com","password":"GLgroup7890T9upWPVp4E7lCmong4oHrEqD","server":"https://login.salesforce.com"}}
      - NON_EXISTENT_SERVER={"driver":"mssql","name":"no_server","config":{"server":"no_server.pants.monkey.underware","password":"vagrant","userName":"vagrant","options":{"port":1433}}}
      - LOCK_DIRECTORY=~/tmp
      - FORKS=1
      - NEW_RELIC_APP_NAME=epiops-dev,services-dev
      - NEW_RELIC_NO_CONFIG_FILE=true
      - NEW_RELIC_LICENSE_KEY=bd51b51debfc060bba7f64f71e6dc22a41a6c3d6
      - NEW_RELIC_LABELS=ENVIRONMENT:DEV;
      - ENABLE_TEMPLATE_ACLS=DISABLED
    depends_on:
      - mysql
      - mssql
  epiquerytest:
    build: 
      dockerfile: ./Dockerfile
    environment:
      - PORT=8080
      - TEMPLATE_DIRECTORY=/var/app/difftest/templates
      - CONNECTIONS=EPI_C_MSSQL_O EPI_C_MSSQL EPI_C_FILE EPI_C_MYSQL EPI_C_RENDER SFDC NON_EXISTENT_SERVER EPI_C_TIMESOUT EPI_C_MYSQL_BULK
      - EPI_C_FILE={"driver":"file","config":{},"name":"file"}
      - EPI_C_RENDER={"driver":"render","config":{},"name":"render"}
      - EPI_C_MSSQL={"driver":"mssql","name":"mssql","config":{"server":"mssql","password":"YourV3ryStrong!Passw0rd","userName":"SA","options":{"port":1433, "requestTimeout":0}}}
      - EPI_C_MSSQL_O={"driver":"mssql_o","name":"mssql_o","config":{"server":"mssql","password":"YourV3ryStrong!Passw0rd","userName":"SA","options":{"port":1433, "requestTimeout":0}}}
      - EPI_C_TIMESOUT={"driver":"mssql","name":"timesout","config":{"server":"localhost","password":"vagrant","userName":"vagrant","options":{"port":1433, "requestTimeout":1}}}
      - EPI_C_MYSQL={"name":"mysql","driver":"mysql","config":{"host":"mysql","user":"root","password":"mysql_root_password"}}
      - EPI_C_MYSQL_BULK={"name":"mysql_bulk", "type":"bulk","driver":"mysql","config":{"host":"mysql","user":"root","password":"mysql_root_password"}}
      - SFDC={"name":"sfdc","driver":"salesforce","config":{"userName":"financeintegration@glgroup.com","password":"GLgroup7890T9upWPVp4E7lCmong4oHrEqD","server":"https://login.salesforce.com"}}
      - NON_EXISTENT_SERVER={"driver":"mssql","name":"no_server","config":{"server":"no_server.pants.monkey.underware","password":"vagrant","userName":"vagrant","options":{"port":1433}}}
      - LOCK_DIRECTORY=~/tmp
      - FORKS=1
      - NEW_RELIC_APP_NAME=epiops-dev,services-dev
      - NEW_RELIC_NO_CONFIG_FILE=true
      - NEW_RELIC_LICENSE_KEY=bd51b51debfc060bba7f64f71e6dc22a41a6c3d6
      - NEW_RELIC_LABELS=ENVIRONMENT:DEV;
      - EPI_TEST_SERVER=epiquery
      - ENABLE_TEMPLATE_ACLS=DISABLED
    add_docker: true
    depends_on:
      - epiquery
  
  dockercfg_generator:
    image: codeship/aws-ecr-dockercfg-generator
    add_docker: true
    encrypted_env_file: aws.env.encrypted
