#! /usr/bin/env bash
MY_ORIGIN_URL=`git config -l | grep remote.origin.url | sed -e s[remote.origin.url=[[g`
REPO_NAME=`basename ${MY_ORIGIN_URL}`
ORIGIN_ROOT=${MY_ORIGIN_URL%/${REPO_NAME}}
TEMPLATES_REPO_NAME=${REPO_NAME/.git/-templates.git}
TEMPLATE_ORIGIN_URL=${ORIGIN_ROOT}/${TEMPLATES_REPO_NAME}
TEMPLATE_ORIGIN_URL=${ORIGIN_URL-${TEMPLATE_REPO_URL}}
if [ -d templates ]; then
  rm -rf ./templates
fi
git clone ${TEMPLATE_ORIGIN_URL} templates
