#! /usr/bin/env bash
exec 2>&1
# enable ACLs, this test is run in a docker container with epiquery, as such the epiquery process
# is always pid 1
kill -SIGUSR2 1
curl -s -H "jwt-test: 1" http://${EPI_TEST_SERVER}:8080/epiquery1/mssql/test/acl_tests.mustache
# disable ACLs
kill -SIGUSR1 1
