#! /usr/bin/env bash
exec 2>&1
# enable ACLs
docker kill --signal=SIGUSR2 epiquery > /dev/null 2>&1
curl -s http://${EPI_TEST_SERVER}:8080/epiquery1/mssql/test/acl_tests.mustache
# disable ACLs
docker kill --signal=SIGUSR1 epiquery > /dev/null 2>&1

