#! /usr/bin/env bash
# vi: ft=sh
curl -s 'http://localhost:8080/simple/mssql/test/datetime_parameter_values_for_null.sql' -H 'Content-type:application/json' --data '{"datetime":"Wed Oct 25 2017 13:19:40 GMT-0500 (CDT)", "nullDatetime":null,"stringNullDatetime":"null","stringUndefinedDatetime":"undefined"}' | jq .
