#! /usr/bin/env bash
exec 2>&1
# enable ACLs, this test is run in a docker container with epiquery, as such the epiquery process
# is always pid 1
kill -SIGUSR2 1
curl -s http://${EPI_TEST_SERVER}:8080/diagnostic | jq '.aclsEnabled'
# disable ACLs
kill -SIGUSR1 1
curl -s http://${EPI_TEST_SERVER}:8080/diagnostic | jq '.aclsEnabled'
# enable ACLs
kill -SIGUSR2 1
curl -s http://${EPI_TEST_SERVER}:8080/diagnostic | jq '.aclsEnabled'
# leave the ACLs disabled for the other tests
kill -SIGUSR1 1
