#! /usr/bin/env bash
exec 2>&1
# enable ACLs
for pid in $(ps aux | grep epistream.coffee | grep -v grep | awk '{print($2)}'); do kill -SIGUSR2 ${pid}; done
curl -s http://${EPI_TEST_SERVER}:8080/diagnostic | jq '.aclsEnabled'
# disable ACLs
for pid in $(ps aux | grep epistream.coffee | grep -v grep | awk '{print($2)}'); do kill -SIGUSR1 ${pid}; done
curl -s http://${EPI_TEST_SERVER}:8080/diagnostic | jq '.aclsEnabled'
# enable ACLs
for pid in $(ps aux | grep epistream.coffee | grep -v grep | awk '{print($2)}'); do kill -SIGUSR2 ${pid}; done
curl -s http://${EPI_TEST_SERVER}:8080/diagnostic | jq '.aclsEnabled'
# leave the ACLs disabled for the other tests
for pid in $(ps aux | grep epistream.coffee | grep -v grep | awk '{print($2)}'); do kill -SIGUSR1 ${pid}; done