#! /usr/bin/env bash
exec 2>&1
# enable ACLs
EPI_CONAINER=$(docker ps | grep "./epistream.coffee" | awk '{print $1}')

docker kill --signal=SIGUSR2 ${EPI_CONAINER} > /dev/null 2>&1
curl -s http://${EPI_TEST_SERVER}:8080/diagnostic | jq '.aclsEnabled'
# disable ACLs
docker kill --signal=SIGUSR1 ${EPI_CONAINER} > /dev/null 2>&1
curl -s http://${EPI_TEST_SERVER}:8080/diagnostic | jq '.aclsEnabled'
# enable ACLs
docker kill --signal=SIGUSR2 ${EPI_CONAINER} > /dev/null 2>&1
curl -s http://${EPI_TEST_SERVER}:8080/diagnostic | jq '.aclsEnabled'
# leave the ACLs disabled for the other tests
docker kill --signal=SIGUSR1 ${EPI_CONAINER} > /dev/null 2>&1
