#! /usr/bin/env bash
[ -r ~/.epiquery2/config ] && source ~/.epiquery2/config
./difftest/bin/templateRunner.coffee --templatePath ${TEMPLATE_DIRECTORY}/test/echo_enumerate.dot --context '{"pants":"blue jeans","message":"Clint Rulez!!!"}'
