#! /usr/bin/env bash
exec 2>&1
curl -s http://${EPI_TEST_SERVER}:8080/simple/mssql/test/json_and_not.mustache --data '{"json":"json“","notjson":"nope“ not json", "json_data":"json_data“"}' -H 'Content-Type: application/json' | jq .
