#!/usr/bin/env bash
# vi: ft=sh
curl -s "http://${EPI_TEST_SERVER}:8080/simple/mssql/test/param-json-large-json-data.sql" \
  --header 'Content-Type: application/json' \
  --data @./difftest/test-data/26mb-of-json | jq .
  #--data '{"message":"catpants","array":[1,2,3,4,5,6,7]}' | jq . 
  
