#!/usr/bin/env bash
# vi: ft=sh
# pass an array to a json object type and verify its still parsed as json
curl -s "http://${EPI_TEST_SERVER}:8080/simple/mssql/test/param-json-object-array.mustache" \
  --header 'Content-Type: application/json' \
  --data '{"myJson": [{"apple": "honeycrisp"}, {"apple": "red delicious"}]}' | jq .
