#!/usr/bin/env bash
# vi: ft=sh
# pass an array to a json object type and verify its still parsed as json
curl -s "http://${EPI_TEST_SERVER}:8080/simple/mssql/test/param_json_date.sql" \
  --header 'Content-Type: application/json' \
  --data '{"myJson": ["honeycrisp", "red delicious"],"datetime":"04/04/2023 04:10:57"}' | jq .
