#!/usr/bin/env bash
# vi: ft=sh
# pass an array to a json object type and verify its still parsed as json
curl -s "http://${EPI_TEST_SERVER}:8080/simple/mssql/test/param-json-multiple-json.sql" \
  --header 'Content-Type: application/json' \
  --data '{"my_object_1": {"name": "Thor", "planet": "Asgard"}, "my_object_2": ["honeycrisp", "red delicious"]}' | jq .
