#! /usr/bin/env bash
curl -s http://${EPI_TEST_SERVER}:8080/simple/mssql/test/param-deep-subobject.sql -H 'Content-Type: application/json' --data '{"user": {"userId": 30, "name": "jim", "pet": {"type": "dog", "detail": {"name": "echo", "color": "black", "breed": "cocker spaniel"}}}}' | jq .
