#! /usr/bin/env bash
MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
curl -s http://localhost:8080/simple/mssql/test/mssql_suser_a
echo
curl -s http://localhost:8080/simple/mssql/test/mssql_suser_b
echo
curl http://localhost:8080/templateToConnectionMap \
    -H 'Content-Type: application/json' \
    --data-binary "@${MY_DIR}/../etc/template_config_map_swapped.json"
echo
curl -s http://localhost:8080/simple/mssql/test/mssql_suser_a
echo
curl -s http://localhost:8080/simple/mssql/test/mssql_suser_b
echo
curl http://localhost:8080/templateToConnectionMap \
    -H 'Content-Type: application/json' \
    --data-binary "@${MY_DIR}/../etc/template_config_map_orig.json"
