#! /usr/bin/env bash
#exec > file_emit.log 2>&1
curl -s "http://${EPI_TEST_SERVER-localhost:8080}/sse?client_id=2" &
sleep .1
curl -s "http://${EPI_TEST_SERVER-localhost:8080}/render/test/1000_rows?client_id=2&close_on_end=true"
wait
