#! /usr/bin/env bash
#exec > file_emit.log 2>&1
SSE_OUT=`mktemp ${TMPDIR}/sse.XXXXX`
REQ_OUT=`mktemp ${TMPDIR}/req.XXXXX`
CLOSE_OUT=`mktemp ${TMPDIR}/close.XXXX`

curl -s 'http://localhost:8080/sse?client_id=2' > ${SSE_OUT} 2>&1 &
sleep .1
curl -s 'http://localhost:8080/this_is_wrong/test/mysql_servername?client_id=2&close_on_end=true' > ${REQ_OUT} 2>&1 
curl -s 'http://localhost:8080/close/2' > ${CLOSE_OUT} 2>&1
cat ${REQ_OUT} ${SSE_OUT} ${CLOSE_OUT}
wait
