#! /usr/bin/env bash
#exec > file_emit.log 2>&1
curl -s 'http://localhost:8080/sse?client_id=2' &
sleep .1
curl -s 'http://localhost:8080/this_is_wrong/test/mysql_servername?client_id=2&close_on_end=true'
curl -s 'http://localhost:8080/close/2'
wait
