#! /usr/bin/env bash
#exec > file_emit.log 2>&1
curl -s 'http://localhost:8080/sse?client_id=2' &
sleep .1
curl -s 'http://localhost:8080/mssql/test/echo.mustache?client_id=2&close_on_end=true&message=hello' &
wait
