#! /usr/bin/env bash
#exec > file_emit.log 2>&1
curl -s 'http://localhost:8080/sse?client_id=2' &
sleep .1
curl -s 'http://localhost:8080/mysql/test/mysql_multiple_row_select?client_id=2&close_on_end=true' &
wait
