# vi:syntax=yaml
#TODO: this should only happen if tests.yml passes - merge them into one file?
name: Build Image and Push to ECR
on:
  push:
    # You can set these branches to any that you want to build and push images from
    branches:
      - gds
      - gds2
      - salesforce-connect
      - salesforce-connect-v2
      - epi-mysql
jobs:
  unit-test:
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: YourV3ryStrong!Passw0rd
      mysql:
        image: mysql:5.7.22
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: epiquery
          MYSQL_ROOT_PASSWORD: mysql_root_password
      sfdc:
        image: glgresearch/sfdc-with-drakov:e04eea15
        ports:
          - 80:80
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.3.1
      - name: Install, lint, and test
        run: |
          npm install
          npm run lint --if-present
          npm test
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.3.1
      - name: Update hosts file
        run: echo '127.0.0.1 mssql mysql sfdc' | sudo tee --append /etc/hosts
      - name: pull images
        run: |
          docker pull glgresearch/sfdc-with-drakov:e04eea15
          docker pull mcr.microsoft.com/mssql/server:2017-latest
          docker pull mysql:5.7.22
      - name: start docker containers
        run: docker-compose up --detach
      - name: make test
        env:
          CONNECTIONS: 'EPI_C_FILE EPI_C_MSSQL_O EPI_C_MSSQL EPI_C_MYSQL_BULK EPI_C_MYSQL EPI_C_RENDER EPI_C_SFDC EPI_C_SFDC_V2 EPI_C_SNOWFLAKE EPI_C_TIMESOUT NON_EXISTENT_SERVER'
          DEBUG: true          # yamllint disable-line rule:indentation
          DIFFTEST_QUIET: false
          ENABLE_TEMPLATE_ACLS: DISABLED
          EPI_C_FILE: '{"driver":"file","name":"file","config":{}}'
          EPI_C_MSSQL_O: '{"driver":"mssql_o","name":"mssql_o","config":{"server":"mssql","password":"YourV3ryStrong!Passw0rd","userName":"SA","options":{"port":1433, "requestTimeout":0}}}'
          EPI_C_MSSQL: '{"driver":"mssql","name":"mssql","config":{"server":"mssql","password":"YourV3ryStrong!Passw0rd","userName":"SA","options":{"port":1433, "requestTimeout":0}}}'
          EPI_C_MYSQL_BULK: '{"driver":"mysql","name":"mysql_bulk","type":"bulk","config":{"host":"mysql","user":"root","password":"mysql_root_password"}}'
          EPI_C_MYSQL: '{"driver":"mysql","name":"mysql","config":{"host":"mysql","user":"root","password":"mysql_root_password"}}'
          EPI_C_RENDER: '{"driver":"render","name":"render","config":{}}'
          EPI_C_SFDC: '{"driver":"salesforce","name":"sfdc","config":{"userName":"","password":"","server":"http://sfdc"}}'
          EPI_C_SFDC_V2: '{"driver":"salesforce_v2","name":"sfdc_v2","config":{"userName":"","password":"","server":"http://sfdc"}}'
          EPI_C_SNOWFLAKE: '{"driver":"snowflake","name":"snowflake","config":{"account":"${{ secrets.SNOWFLAKE_INTEGRATION_TEST_ACCOUNT_ID }}", "warehouse":"EPIQUERY_PRODUCTION", "username":"${{ secrets.SNOWFLAKE_INTEGRATION_TEST_USERNAME }}", "password":"${{ secrets.SNOWFLAKE_INTEGRATION_TEST_PASSWORD }}"}}'
          EPI_C_TIMESOUT: '{"driver":"mssql","name":"timesout","config":{"server":"localhost","password":"vagrant","userName":"vagrant","options":{"port":1433, "requestTimeout":1}}}'
          EPI_SCREAMER_URL: https://services.glgresearch.com/epi-screamer/epiquery
          EPI_TEST_SERVER: localhost
          FORKS: 1
          LOCK_DIRECTORY: ~/tmp
          NODE_ENV: development
          NON_EXISTENT_SERVER: '{"driver":"mssql","name":"no_server","config":{"server":"no_server.pants.monkey.underware","password":"vagrant","userName":"vagrant","options":{"port":1433}}}'
          PORT: 8080
          TEMPLATE_DIRECTORY: ${{ github.workspace }}/difftest/templates/
        run: |
          TZ=UTC make start &
          ./bin/wait-for-epi
          DEBUG= make test
  build-and-deploy:
    runs-on: ubuntu-20.04
    needs: [unit-test, integration-test]
    steps:
      # Checks out the code from this repo
      - uses: actions/checkout@main

      # Builds a docker image from ./dockerfile, and pushes it to our ECR repository
      - uses: glg-public/build-and-deploy-ecr@main
        with:
          ecr_uri: ${{secrets.GLGAPP_ECR_URI}}
          access_key_id: ${{secrets.GLGAPP_ECR_AWS_ACCESS_KEY_ID}}
          secret_access_key: ${{secrets.GLGAPP_ECR_AWS_SECRET_ACCESS_KEY}}
          env_file: docker.env
          healthcheck: /diagnostic
          port: 8080
